pipeline {
    agent {
        label  'AGENT-1'
    }
    environment {
        appVersion = ""
        ACC_ID  = "888947293288"
        REGION  = "us-east-1" 
        PROJECT = "roboshop" 
        COMPONENT = "catalogue" 
    }
    options {
        timeout(time:30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    //BUILD 
    stages{
        stage ('init') {
            steps {
                script {
                       withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                         sh """
                           cd 00-vpc
                           terraform init -reconfigure 
                         """  
                       }
                
                }
            }
        }
        stage ('plan') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                           cd 00-vpc
                           terraform plan  
                        """ 
                    }
                }
            }
        }
        stage('apply') {
            input {
                message "we should continue?"
                ok "yes, we should" 
                submitter "alice,bob"
            }
            steps{
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                           cd 00-vpc 
                           terraform apply -auto-approve 
                        """ 
                    }
                }
            }
        }
        // Down stream job 
        stage ('Trigger SG') {
            steps {
                script {
                    build job: '10-sg' 
                    propagate: false //even sg fails vpc will not be effected 
                    wait: false //vpc will not wait for sg pipeline completion 
                }
            }
        }
    }
    
    post {
        always {
            echo "I will always say HELLO AGAIN!"
            deleteDir()
        }
        success {
            echo "Success"
        }
        failure {
            echo "Failure"
        }
    }
}