pipeline {
    agent {
        label  'AGENT-1'
    }
    environment {
        appVersion = ""
        ACC_ID  = "888947293288"
        REGION  = "us-east-1" 
        PROJECT = "roboshop" 
        COMPONENT = "catalogue" 
    }
    options {
        timeout(time:30, unit: 'MINUTES')
        disableConcurrentBuilds()
    }
    //BUILD 
    stages{
        stage ('init') {
            steps {
                script {
                    sh """
                       withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                           cd 00-vpc
                           terraform init -reconfigure 
                       }
                    """
                }
            }
        }
    }
    post {
        always {
            echo "I will always say HELLO AGAIN!"
            deleteDir()
        }
        success {
            echo "Success"
        }
        failure {
            echo "Failure"
        }
    }
}