pipeline {
    agent {
       label 'AGENT-1'
    }
    environment {
        appVersion = '' 
        REGION  =  "us-east-1" 
        ACC_ID  = "888947293288" 
        PROJECT = "roboshop"
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds() 
        ansiColor('xterm') 
    }
    // Build 
    stages  {
        stage('init') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """
                            cd 10-sg
                            terraform init -reconfigure
                        """
                    }
                }
            }
        }
        stage('plan') {
            steps {
                script{
                    withAWS(credentials: 'aws-creds', region: 'us-east-1') {
                        sh """ 
                           cd 10-sg
                           terraform plan
                        """
                    }
                }
            }
        }
        stage('apply') {
            steps {
                script {
                    withAWS(credentials: 'aws-creds',region: 'us-east-1') {
                        sh """ 
                           cd 10-sg 
                           terraform apply -auto-approve 
                        """ 
                    } 
                    
                }
            }
        }
        stage('Bastion EKS ACM ALB') {
            parallel {
                stage('Trigger Bation') {
                    steps {
                        script {
                            build job: '20-bastion' 
                               propagate: false // even sg fails vpc will not be effected 
                               wait: false // vpc will not wait for sg pipeline creation 
                        }
                    }
                }
                stage('Trigger EKS') {
                    steps {
                        script {
                            build job: '80-eks' 
                              propagate: false //even sg fails vpc will not be effected 
                              wait: false  // vpc will not wair for sg pipeline creation 
                        }
                    }
                }
                stage('Trigger ACM') {
                    steps {
                        script {
                            build job: '60-acm' 
                               propagate: false // even sg fails vpc will not be effected 
                               wait: false // vpc will not wait for sg pipeline creation 
                        }
                    }
                }
            }
        }
        stage('Trigger ALB') {
            steps {
                script {
                    build job: '70-frontend-alb'
                       propagate: false // even sg fails vpc will not be effected 
                       wait: false // vpc will not wait for sg pipeline creation 
                }
            }
        }
    }
    post {
        always {
            echo "i will always say Hello Again!"
            deleteDir()
        }
        success {
            echo "Hello Success"
        }
        failure {
            echo "Hello Failure"
        }
    }
}